services:
  mongo_db:
    container_name: mongo_docker_adoptme
    image: mongo:latest
    ports:
      - 27017:27017
  api:
    container_name: api_docker_adoptme
    image: natyfernandez/server-docker:1.0.0
    ports:
      - 8000:8000
    environment:
      MONGO_URI: mongodb://mongo_db:27017/adoptme